workspace "tensorflow/rust" "Rust language bindings for TensorFlow" {

    model {
        tensorflowrust = softwareSystem "tensorflow/rust" "Rust language bindings for TensorFlow." {
            tensorflow = container "tensorflow" "Rust language bindings for TensorFlow." "Rust" {
                buffer = component "Buffer" "" "Rust Struct"
                checkpointMaker = component "CheckpointMaker" "" "Rust Struct"
                contextOptions = component "ContextOptions" "" "Rust Struct"
                context = component "Context" "" "Rust Struct"
                add = component "Add" "" "Rust Struct"
                rawOps = component "raw_ops" "" "Rust Module"
                readonlyTensor = component "ReadonlyTensor" "" "Rust Struct"
                tensorHandle = component "TensorHandle" "" "Rust Struct"
                toTensorHandle = component "ToTensorHandle" "" "Rust Trait"
                opLevel = component "OpLevel" "" "Rust Enum"
                expr = component "Expr" "" "Rust Struct"
                shapeHint = component "ShapeHint" "" "Rust Enum"
                exprImpl = component "ExprImpl" "" "Rust Trait"
                truncateDiv = component "TruncateDiv" "" "Rust Struct"
                neg = component "Neg" "" "Rust Struct"
                variable = component "Variable" "" "Rust Struct"
                placeholder = component "Placeholder" "" "Rust Struct"
                constant = component "Constant" "" "Rust Struct"
                assign = component "Assign" "" "Rust Struct"
                anyExpr = component "AnyExpr" "" "Rust Trait"
                compiler = component "Compiler" "" "Rust Struct"
                importGraphDefOptions = component "ImportGraphDefOptions" "" "Rust Struct"
                importGraphDefResults = component "ImportGraphDefResults" "" "Rust Struct"
                graph = component "Graph" "" "Rust Struct"
                operationIter = component "OperationIter" "" "Rust Struct"
                attrMetadata = component "AttrMetadata" "" "Rust Struct"
                operation = component "Operation" "" "Rust Struct"
                input = component "Input" "" "Rust Struct"
                output = component "Output" "" "Rust Struct"
                outputName = component "OutputName" "" "Rust Struct"
                operationDescription = component "OperationDescription" "" "Rust Struct"
                functionOptions = component "FunctionOptions" "" "Rust Struct"
                function = component "Function" "" "Rust Struct"
                recordWriter = component "RecordWriter" "" "Rust Struct"
                recordReadError = component "RecordReadError" "" "Rust Enum"
                recordReader = component "RecordReader" "" "Rust Struct"
                expr = component "expr" "" "Rust Module"
                io = component "io" "" "Rust Module"
                ops = component "ops" "" "Rust Module"
                train = component "train" "" "Rust Module"
                eager = component "eager" "" "Rust Module"
                status = component "Status" "" "Rust Struct"
                sessionOptions = component "SessionOptions" "" "Rust Struct"
                tensorType = component "TensorType" "" "Rust Trait"
                bFloat16 = component "BFloat16" "" "Rust Struct"
                anyTensor = component "AnyTensor" "" "Rust Trait"
                tensorInner = component "TensorInner" "" "Rust Trait"
                tensorDataCRepr = component "TensorDataCRepr" "" "Rust Struct"
                tensorDataNoCRepr = component "TensorDataNoCRepr" "" "Rust Struct"
                tensor = component "Tensor" "" "Rust Struct"
                library = component "Library" "" "Rust Struct"
                opList = component "OpList" "" "Rust Struct"
                opDef = component "OpDef" "" "Rust Struct"
                opArgDef = component "OpArgDef" "" "Rust Struct"
                opAttrDef = component "OpAttrDef" "" "Rust Struct"
                shape = component "Shape" "" "Rust Struct"
                optionInsertWithResult = component "OptionInsertWithResult" "" "Rust Trait"
                pluggableDeviceLibrary = component "PluggableDeviceLibrary" "" "Rust Struct"
                allocationDescription = component "AllocationDescription" "" "Rust Struct"
                attrValue = component "AttrValue" "" "Rust Struct"
                attrValueOneofValue = component "AttrValue_oneof_value" "" "Rust Enum"
                attrValueListValue = component "AttrValue_ListValue" "" "Rust Struct"
                nameAttrList = component "NameAttrList" "" "Rust Struct"
                jobDef = component "JobDef" "" "Rust Struct"
                clusterDef = component "ClusterDef" "" "Rust Struct"
                gPUOptions = component "GPUOptions" "" "Rust Struct"
                gPUOptionsExperimental = component "GPUOptions_Experimental" "" "Rust Struct"
                gPUOptionsExperimentalVirtualDevices = component "GPUOptions_Experimental_VirtualDevices" "" "Rust Struct"
                gPUOptionsExperimentalStreamMergeOptions = component "GPUOptions_Experimental_StreamMergeOptions" "" "Rust Struct"
                optimizerOptions = component "OptimizerOptions" "" "Rust Struct"
                optimizerOptionsLevel = component "OptimizerOptions_Level" "" "Rust Enum"
                optimizerOptionsGlobalJitLevel = component "OptimizerOptions_GlobalJitLevel" "" "Rust Enum"
                graphOptions = component "GraphOptions" "" "Rust Struct"
                threadPoolOptionProto = component "ThreadPoolOptionProto" "" "Rust Struct"
                sessionMetadata = component "SessionMetadata" "" "Rust Struct"
                configProto = component "ConfigProto" "" "Rust Struct"
                configProtoExperimental = component "ConfigProto_Experimental" "" "Rust Struct"
                configProtoExperimentalMlirBridgeRollout = component "ConfigProto_Experimental_MlirBridgeRollout" "" "Rust Enum"
                runOptions = component "RunOptions" "" "Rust Struct"
                runOptionsExperimental = component "RunOptions_Experimental" "" "Rust Struct"
                runOptionsExperimentalRunHandlerPoolOptions = component "RunOptions_Experimental_RunHandlerPoolOptions" "" "Rust Struct"
                runOptionsTraceLevel = component "RunOptions_TraceLevel" "" "Rust Enum"
                runMetadata = component "RunMetadata" "" "Rust Struct"
                runMetadataFunctionGraphs = component "RunMetadata_FunctionGraphs" "" "Rust Struct"
                tensorConnection = component "TensorConnection" "" "Rust Struct"
                callableOptions = component "CallableOptions" "" "Rust Struct"
                coordinatedJob = component "CoordinatedJob" "" "Rust Struct"
                coordinationServiceConfig = component "CoordinationServiceConfig" "" "Rust Struct"
                costGraphDef = component "CostGraphDef" "" "Rust Struct"
                costGraphDefNode = component "CostGraphDef_Node" "" "Rust Struct"
                costGraphDefNodeInputInfo = component "CostGraphDef_Node_InputInfo" "" "Rust Struct"
                costGraphDefNodeOutputInfo = component "CostGraphDef_Node_OutputInfo" "" "Rust Struct"
                costGraphDefAggregatedCost = component "CostGraphDef_AggregatedCost" "" "Rust Struct"
                debugTensorWatch = component "DebugTensorWatch" "" "Rust Struct"
                debugOptions = component "DebugOptions" "" "Rust Struct"
                debuggedSourceFile = component "DebuggedSourceFile" "" "Rust Struct"
                debuggedSourceFiles = component "DebuggedSourceFiles" "" "Rust Struct"
                fullTypeDef = component "FullTypeDef" "" "Rust Struct"
                fullTypeDefOneofAttr = component "FullTypeDef_oneof_attr" "" "Rust Enum"
                fullTypeId = component "FullTypeId" "" "Rust Enum"
                functionDefLibrary = component "FunctionDefLibrary" "" "Rust Struct"
                functionDef = component "FunctionDef" "" "Rust Struct"
                functionDefArgAttrs = component "FunctionDef_ArgAttrs" "" "Rust Struct"
                gradientDef = component "GradientDef" "" "Rust Struct"
                registeredGradient = component "RegisteredGradient" "" "Rust Struct"
                graphDef = component "GraphDef" "" "Rust Struct"
                graphDebugInfo = component "GraphDebugInfo" "" "Rust Struct"
                graphDebugInfoFileLineCol = component "GraphDebugInfo_FileLineCol" "" "Rust Struct"
                graphDebugInfoStackTrace = component "GraphDebugInfo_StackTrace" "" "Rust Struct"
                metaGraphDef = component "MetaGraphDef" "" "Rust Struct"
                metaGraphDefMetaInfoDef = component "MetaGraphDef_MetaInfoDef" "" "Rust Struct"
                collectionDef = component "CollectionDef" "" "Rust Struct"
                collectionDefOneofKind = component "CollectionDef_oneof_kind" "" "Rust Enum"
                collectionDefNodeList = component "CollectionDef_NodeList" "" "Rust Struct"
                collectionDefBytesList = component "CollectionDef_BytesList" "" "Rust Struct"
                collectionDefInt64List = component "CollectionDef_Int64List" "" "Rust Struct"
                collectionDefFloatList = component "CollectionDef_FloatList" "" "Rust Struct"
                collectionDefAnyList = component "CollectionDef_AnyList" "" "Rust Struct"
                tensorInfo = component "TensorInfo" "" "Rust Struct"
                tensorInfoOneofEncoding = component "TensorInfo_oneof_encoding" "" "Rust Enum"
                tensorInfoCooSparse = component "TensorInfo_CooSparse" "" "Rust Struct"
                tensorInfoCompositeTensor = component "TensorInfo_CompositeTensor" "" "Rust Struct"
                signatureDef = component "SignatureDef" "" "Rust Struct"
                assetFileDef = component "AssetFileDef" "" "Rust Struct"
                nodeDef = component "NodeDef" "" "Rust Struct"
                nodeDefExperimentalDebugInfo = component "NodeDef_ExperimentalDebugInfo" "" "Rust Struct"
                opDef = component "OpDef" "" "Rust Struct"
                opDefArgDef = component "OpDef_ArgDef" "" "Rust Struct"
                opDefAttrDef = component "OpDef_AttrDef" "" "Rust Struct"
                opDeprecation = component "OpDeprecation" "" "Rust Struct"
                opList = component "OpList" "" "Rust Struct"
                resourceHandleProto = component "ResourceHandleProto" "" "Rust Struct"
                resourceHandleProtoDtypeAndShape = component "ResourceHandleProto_DtypeAndShape" "" "Rust Struct"
                autoParallelOptions = component "AutoParallelOptions" "" "Rust Struct"
                scopedAllocatorOptions = component "ScopedAllocatorOptions" "" "Rust Struct"
                rewriterConfig = component "RewriterConfig" "" "Rust Struct"
                rewriterConfigCustomGraphOptimizer = component "RewriterConfig_CustomGraphOptimizer" "" "Rust Struct"
                rewriterConfigToggle = component "RewriterConfig_Toggle" "" "Rust Enum"
                rewriterConfigCpuLayout = component "RewriterConfig_CpuLayout" "" "Rust Enum"
                rewriterConfigNumIterationsType = component "RewriterConfig_NumIterationsType" "" "Rust Enum"
                rewriterConfigMemOptType = component "RewriterConfig_MemOptType" "" "Rust Enum"
                rPCOptions = component "RPCOptions" "" "Rust Struct"
                savedModel = component "SavedModel" "" "Rust Struct"
                savedObjectGraph = component "SavedObjectGraph" "" "Rust Struct"
                savedObject = component "SavedObject" "" "Rust Struct"
                savedObjectOneofKind = component "SavedObject_oneof_kind" "" "Rust Enum"
                savedUserObject = component "SavedUserObject" "" "Rust Struct"
                savedAsset = component "SavedAsset" "" "Rust Struct"
                savedFunction = component "SavedFunction" "" "Rust Struct"
                capturedTensor = component "CapturedTensor" "" "Rust Struct"
                savedConcreteFunction = component "SavedConcreteFunction" "" "Rust Struct"
                savedBareConcreteFunction = component "SavedBareConcreteFunction" "" "Rust Struct"
                savedConstant = component "SavedConstant" "" "Rust Struct"
                savedVariable = component "SavedVariable" "" "Rust Struct"
                functionSpec = component "FunctionSpec" "" "Rust Struct"
                functionSpecJitCompile = component "FunctionSpec_JitCompile" "" "Rust Enum"
                savedResource = component "SavedResource" "" "Rust Struct"
                saveableObject = component "SaveableObject" "" "Rust Struct"
                saverDef = component "SaverDef" "" "Rust Struct"
                saverDefCheckpointFormatVersion = component "SaverDef_CheckpointFormatVersion" "" "Rust Enum"
                allocationRecord = component "AllocationRecord" "" "Rust Struct"
                allocatorMemoryUsed = component "AllocatorMemoryUsed" "" "Rust Struct"
                nodeOutput = component "NodeOutput" "" "Rust Struct"
                memoryStats = component "MemoryStats" "" "Rust Struct"
                nodeExecStats = component "NodeExecStats" "" "Rust Struct"
                deviceStepStats = component "DeviceStepStats" "" "Rust Struct"
                stepStats = component "StepStats" "" "Rust Struct"
                structuredValue = component "StructuredValue" "" "Rust Struct"
                structuredValueOneofKind = component "StructuredValue_oneof_kind" "" "Rust Enum"
                noneValue = component "NoneValue" "" "Rust Struct"
                listValue = component "ListValue" "" "Rust Struct"
                tupleValue = component "TupleValue" "" "Rust Struct"
                dictValue = component "DictValue" "" "Rust Struct"
                pairValue = component "PairValue" "" "Rust Struct"
                namedTupleValue = component "NamedTupleValue" "" "Rust Struct"
                tensorSpecProto = component "TensorSpecProto" "" "Rust Struct"
                boundedTensorSpecProto = component "BoundedTensorSpecProto" "" "Rust Struct"
                typeSpecProto = component "TypeSpecProto" "" "Rust Struct"
                typeSpecProtoTypeSpecClass = component "TypeSpecProto_TypeSpecClass" "" "Rust Enum"
                tensorProto = component "TensorProto" "" "Rust Struct"
                variantTensorDataProto = component "VariantTensorDataProto" "" "Rust Struct"
                tensorDescription = component "TensorDescription" "" "Rust Struct"
                tensorShapeProto = component "TensorShapeProto" "" "Rust Struct"
                tensorShapeProtoDim = component "TensorShapeProto_Dim" "" "Rust Struct"
                trackableObjectGraph = component "TrackableObjectGraph" "" "Rust Struct"
                trackableObjectGraphTrackableObject = component "TrackableObjectGraph_TrackableObject" "" "Rust Struct"
                trackableObjectGraphTrackableObjectObjectReference = component "TrackableObjectGraph_TrackableObject_ObjectReference" "" "Rust Struct"
                trackableObjectGraphTrackableObjectSerializedTensor = component "TrackableObjectGraph_TrackableObject_SerializedTensor" "" "Rust Struct"
                trackableObjectGraphTrackableObjectSlotVariableReference = component "TrackableObjectGraph_TrackableObject_SlotVariableReference" "" "Rust Struct"
                registeredSaver = component "RegisteredSaver" "" "Rust Struct"
                serializedDType = component "SerializedDType" "" "Rust Struct"
                dataType = component "DataType" "" "Rust Enum"
                variableDef = component "VariableDef" "" "Rust Struct"
                saveSliceInfoDef = component "SaveSliceInfoDef" "" "Rust Struct"
                variableSynchronization = component "VariableSynchronization" "" "Rust Enum"
                variableAggregation = component "VariableAggregation" "" "Rust Enum"
                verifierConfig = component "VerifierConfig" "" "Rust Struct"
                verifierConfigToggle = component "VerifierConfig_Toggle" "" "Rust Enum"
                versionDef = component "VersionDef" "" "Rust Struct"
                allocationDescription = component "allocation_description" "" "Rust Module"
                attrValue = component "attr_value" "" "Rust Module"
                cluster = component "cluster" "" "Rust Module"
                config = component "config" "" "Rust Module"
                coordinationConfig = component "coordination_config" "" "Rust Module"
                costGraph = component "cost_graph" "" "Rust Module"
                debug = component "debug" "" "Rust Module"
                fullType = component "full_type" "" "Rust Module"
                function = component "function" "" "Rust Module"
                graph = component "graph" "" "Rust Module"
                graphDebugInfo = component "graph_debug_info" "" "Rust Module"
                metaGraph = component "meta_graph" "" "Rust Module"
                nodeDef = component "node_def" "" "Rust Module"
                opDef = component "op_def" "" "Rust Module"
                resourceHandle = component "resource_handle" "" "Rust Module"
                rewriterConfig = component "rewriter_config" "" "Rust Module"
                rpcOptions = component "rpc_options" "" "Rust Module"
                savedModel = component "saved_model" "" "Rust Module"
                savedObjectGraph = component "saved_object_graph" "" "Rust Module"
                saver = component "saver" "" "Rust Module"
                stepStats = component "step_stats" "" "Rust Module"
                structPb = component "struct_pb" "" "Rust Module"
                tensor = component "tensor" "" "Rust Module"
                tensorDescription = component "tensor_description" "" "Rust Module"
                tensorShape = component "tensor_shape" "" "Rust Module"
                trackableObjectGraph = component "trackable_object_graph" "" "Rust Module"
                types = component "types" "" "Rust Module"
                variable = component "variable" "" "Rust Module"
                verifierConfig = component "verifier_config" "" "Rust Module"
                versions = component "versions" "" "Rust Module"
                saveModelError = component "SaveModelError" "" "Rust Struct"
                tensorInfo = component "TensorInfo" "" "Rust Struct"
                signatureDef = component "SignatureDef" "" "Rust Struct"
                metaGraphDef = component "MetaGraphDef" "" "Rust Struct"
                savedModelBuilder = component "SavedModelBuilder" "" "Rust Struct"
                savedModelSaver = component "SavedModelSaver" "" "Rust Struct"
                scope = component "Scope" "" "Rust Struct"
                savedModelBundle = component "SavedModelBundle" "" "Rust Struct"
                session = component "Session" "" "Rust Struct"
                fetchToken = component "FetchToken" "" "Rust Struct"
                sessionRunArgs = component "SessionRunArgs" "" "Rust Struct"
                device = component "Device" "" "Rust Struct"
                minimizeOptions = component "MinimizeOptions" "" "Rust Struct"
                computeGradientsOptions = component "ComputeGradientsOptions" "" "Rust Struct"
                applyGradientsOptions = component "ApplyGradientsOptions" "" "Rust Struct"
                optimizer = component "Optimizer" "" "Rust Trait"
                gradientDescentOptimizer = component "GradientDescentOptimizer" "" "Rust Struct"
                adadeltaOptimizer = component "AdadeltaOptimizer" "" "Rust Struct"
                variable = component "Variable" "" "Rust Struct"
                variableBuilder = component "VariableBuilder" "" "Rust Struct"
                whileBuilder = component "WhileBuilder" "" "Rust Struct"
            }
        }
    }

    views {
        systemContext tensorflowrust "SystemContext" {
            include *
            autoLayout
        }
        container tensorflowrust "Containers" {
            include *
            autoLayout
        }
        component tensorflow "Components_tensorflow" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background "#08427b"
                color "#ffffff"
            }
            element "Software System" {
                background "#1168bd"
                color "#ffffff"
            }
            element "External" {
                background "#999999"
                color "#ffffff"
            }
            element "Container" {
                background "#438dd5"
                color "#ffffff"
            }
            element "Component" {
                background "#85bbf0"
                color "#000000"
            }
            element "Database" {
                shape Cylinder
                background "#438dd5"
                color "#ffffff"
            }
        }
    }
}
